### ISSUE TITLE
怎么确定蓝牙是否关闭

### ISSUE THREAD

**Issue by oubowu** [Mintimate/SleepAndAutoBluetoothAndWifi#1]
睡眠状态起来 我看到wifi是关闭到启动 但是蓝牙一直是开启状态 所以想问下 怎么测试蓝牙睡眠是否关闭 版本是monterey 12.2.1

**Comment by Mintimate** [comment]
这个太简单了，你拿AirPods连接电脑（或者其他蓝牙设备），之后盒盖睡眠，看看AirPods有没有断开即可。Monterey我是没有升级，Bigsur目前正常。

**Comment by oubowu** [comment]
刚刚试了 不行 芭比Q了

**Comment by oubowu** [comment]
╭─    ~ ············································· ✔  at 14:51:39  ─╮
╰─ /usr/local/bin/blueutil -p 0                                              ─╯
zsh: no such file or directory: /usr/local/bin/blueutil
╭─    ~ ········································· 127 ✘  at 14:51:44  ─╮
╰─ blueutil -p 0                                                             ─╯
╭─    ~ ············································· ✔  at 14:52:37  ─╮
╰─ blueutil -p 1                                                             ─╯
╭─    ~ ············································· ✔  at 14:52:52  ─╮
╰─                                                                           ─╯

知道咋回事了 安装路径不对 看了脚本的执行命令
